/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MDCTextField as MdcTextField
} from './components/mdc-text-field/mdc-text-field';

declare global {
  interface HTMLMdcTextFieldElement extends MdcTextField, HTMLElement {
  }
  var HTMLMdcTextFieldElement: {
    prototype: HTMLMdcTextFieldElement;
    new (): HTMLMdcTextFieldElement;
  };
  interface HTMLElementTagNameMap {
    "mdc-text-field": HTMLMdcTextFieldElement;
  }
  interface ElementTagNameMap {
    "mdc-text-field": HTMLMdcTextFieldElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "mdc-text-field": JSXElements.MdcTextFieldAttributes;
    }
  }
  namespace JSXElements {
    export interface MdcTextFieldAttributes extends HTMLAttributes {
      
        label?: string,
        initialValue?: string,
        persistent?: boolean,
        disabled?: boolean
    }
  }
}

