/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@quiver/mdc-button';

import '@quiver/mdc-material';

import '@quiver/mdc-text-field';


import {
  FirebaseAuthentication as FirebaseAuthentication
} from './components/firebase-authentication/firebase-authentication';

declare global {
  interface HTMLFirebaseAuthenticationElement extends FirebaseAuthentication, HTMLElement {
  }
  var HTMLFirebaseAuthenticationElement: {
    prototype: HTMLFirebaseAuthenticationElement;
    new (): HTMLFirebaseAuthenticationElement;
  };
  interface HTMLElementTagNameMap {
    "firebase-authentication": HTMLFirebaseAuthenticationElement;
  }
  interface ElementTagNameMap {
    "firebase-authentication": HTMLFirebaseAuthenticationElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "firebase-authentication": JSXElements.FirebaseAuthenticationAttributes;
    }
  }
  namespace JSXElements {
    export interface FirebaseAuthenticationAttributes extends HTMLAttributes {
      
        email?: boolean,
        phone?: boolean,
        google?: boolean,
        facebook?: boolean,
        twitter?: boolean,
        github?: boolean,
        redirect?: boolean
    }
  }
}

