/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MDCMaterial as MdcMaterial
} from './components/mdc-material/mdc-material';

declare global {
  interface HTMLMdcMaterialElement extends MdcMaterial, HTMLElement {
  }
  var HTMLMdcMaterialElement: {
    prototype: HTMLMdcMaterialElement;
    new (): HTMLMdcMaterialElement;
  };
  interface HTMLElementTagNameMap {
    "mdc-material": HTMLMdcMaterialElement;
  }
  interface ElementTagNameMap {
    "mdc-material": HTMLMdcMaterialElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "mdc-material": JSXElements.MdcMaterialAttributes;
    }
  }
  namespace JSXElements {
    export interface MdcMaterialAttributes extends HTMLAttributes {
      
        elevation?: number,
        transition?: boolean,
        padding?: boolean
    }
  }
}

